=== respinos/glam-sample-generator-rb/schemas/submission_header.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "https://umich.edu/schemas/submission_header.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uri"
    },
    "parent": {
      "type": "string",
      "format": "uri"
    },
    "systemIdentifier": {
      "type": "string",
      "format": "uuid"
    },
    "interactionModel": {
      "type": "string",
      "format": "uri",
      "enum": [
        "urn:umich:lib:dor:model:2026:file:data",
        "urn:umich:lib:dor:model:2026:file:metadata",
        "urn:umich:lib:dor:model:2026:file:description",
        "urn:umich:lib:dor:model:2026:resource:glam",
        "urn:umich:lib:dor:model:2026:resource:fileset",
        "urn:umich:lib:dor:model:2026:rights",
        "urn:umich:lib:dor:model:2026:inventory",
        "urn:umich:lib:dor:model:2026:acl",
        "urn:umich:lib:dor:model:2026:structure"
      ]
    },
    "contentSize": {
      "type": "integer"
    },
    "digests": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "updatedBy": {
      "type": "string"
    },
    "deleted": {
      "type": "boolean"
    },
    "visibility": {
      "type": "string",
      "enum": ["private", "unlisted", "visible", "tombstone"]
    },
    "contentPath": {
      "type": "string"
    },
    "headersVersion": {
      "type": "string",
      "enum": ["1.0"]
    }
  },
  "required": [
    "id",
    "parent",
    "systemIdentifier",
    "interactionModel",
    "updatedAt",
    "headersVersion"
  ],
  "$comment": "Non-resources have additional properties",
"allOf": [
    {
      "if": {
        "properties": {
          "interactionModel": {
            "enum": [
              "urn:umich:lib:dor:model:2026:file:data",
              "urn:umich:lib:dor:model:2026:file:metadata"
            ]
          }
        }
      },
      "then": {
        "properties": {
          "mimeType": { "type": "string" },
          "filename": { "type": "string" }
        },
        "required": ["mimeType", "filename"]
      }
    },
    {
      "if": {
        "properties": {
          "interactionModel": {
            "const": "urn:umich:lib:dor:model:2026:resource:glam"
          }
        }
      },
      "then": {
        "properties": {
          "stakeholderId": { "type": "string" },
          "alternateId": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": { "type": "string" },
                "value": { "type": "string" }
              }
            }
          }
        }
      }
    }
  ]
}

=== respinos/glam-sample-generator-rb/fixtures/00000000-0000-0000-0000-000000000100/xyzzy.0256/pamphlet/.dor/core.dor.json.json
{
  "id": "info:root/xyzzy.0256/pamphlet",
  "parent": "info:root/xyzzy.0256",
  "systemIdentifier": "b20b2aa0-cc96-52a0-b1ef-c0e6833c0cb7",
  "interactionModel": "urn:umich:lib:dor:model:2026:resource:glam",
  "contentSize": 2,
  "digests": [
    "urn:sha-512:27c74670adb75075fad058d5ceaf7b20c4e7786c83bae8a32f626f9782af34c9a33c2046ef60fd2a7878d378e29fec851806bbd9a67878f3a9f1cda4830763fd"
  ],
  "updatedAt": "2026-03-16T17:54:29Z",
  "updatedBy": "dlxsadm",
  "deleted": false,
  "visibility": "visible",
  "contentPath": "core.dor.json",
  "headersVersion": "1.0"
}

=== respinos/glam-sample-generator-rb/fixtures/00000000-0000-0000-0000-000000000001/xyzzy.0001/.dor/core.dor.json.json
{
  "id": "info:root/xyzzy.0001",
  "parent": "info:root",
  "systemIdentifier": "a2745177-391a-5754-90b7-0c71abfa2766",
  "interactionModel": "urn:umich:lib:dor:model:2026:resource:glam",
  "contentSize": 137,
  "digests": [
    "urn:sha-512:a9d0442486f73ced76c3044a502deefea4e0a9c420595a53247b2bb6cc8ee03de783ba932a27ad78d1096b9bdc7572041bfe9a7fee5dc1ba0ea5d044d8c3a614"
  ],
  "updatedAt": "2026-03-16T16:54:24Z",
  "updatedBy": "dlxsadm",
  "deleted": false,
  "visibility": "visible",
  "contentPath": "core.dor.json",
  "headersVersion": "1.0"
}

=== respinos/glam-sample-generator-rb/examples/nested/tinder.28855/.dor/rights.dor.json.json
{
  "id": "info:root/tinder.28855/rights.dor.json",
  "parent": "info:root/tinder.28855",
  "systemIdentifier": "c4b31c45-f609-52c4-b25b-e3bc35bdb9e4",
  "interactionModel": "urn:umich:lib:dor:model:2026:rights",
  "contentSize": 410,
  "digests": [
    "urn:sha-512:d9671c25b1a3c69732fa323d3fb281f9ce027753bb746b6f25dc38162ddfa57de26a7b42902c78cffba16f63f57309c6bb79b3d04c954d9f9a16024d18b82c6a"
  ],
  "updatedAt": "2025-11-05T15:34:56-05:00",
  "updatedBy": "dlxsadm",
  "deleted": false,
  "visibility": "visible",
  "contentPath": "rights.dor.json",
  "headersVersion": "1.0"
}

=== respinos/glam-sample-generator-rb/examples/nested/tinder.28855/.dor/structure.dor.xml.json
{
  "id": "info:root/tinder.28855/structure.dor.xml",
  "parent": "info:root/tinder.28855",
  "systemIdentifier": "e77bd700-7506-5e66-922f-165d36b5cfbb",
  "interactionModel": "urn:umich:lib:dor:model:2026:structure",
  "contentSize": 760,
  "digests": [
    "urn:sha-512:992c7595ab9ea94420b1ef3f3f5262cb5af0d2f6f1c75e9ce2145fd0ef7bbeaabd8cb905ed06d32eabf7c5ea94ec3b20bd8648aa9be9ae76cdf420714ba25f3b"
  ],
  "updatedAt": "2025-11-05T15:34:56-05:00",
  "updatedBy": "dlxsadm",
  "deleted": false,
  "visibility": "visible",
  "contentPath": "structure.dor.xml",
  "headersVersion": "1.0"
}

=== respinos/glam-sample-generator-rb/examples/nested/yhsic1.01027/.dor/structure.dor.xml.json
{
  "id": "info:root/yhsic1.01027/structure.dor.xml",
  "parent": "info:root/yhsic1.01027",
  "systemIdentifier": "b0e41247-768a-5337-8d72-07fc95d395a5",
  "interactionModel": "urn:umich:lib:dor:model:2026:structure",
  "contentSize": 449,
  "digests": [
    "urn:sha-512:215aec92c88ff26bddabc1c8644faad2f83d7d63804d8bb563a1862824b1a0416834a0f5b8fc679f8cf5a6f558c0e1e310e15a47067a24a1aa75d2fd4c52ae90"
  ],
  "updatedAt": "2025-10-28T16:21:47-04:00",
  "updatedBy": "dlxsadm",
  "deleted": false,
  "visibility": "visible",
  "contentPath": "structure.dor.xml",
  "headersVersion": "1.0"
}

=== respinos/glam-sample-generator-rb/fixtures/00000000-0000-0000-0000-000000000001/xyzzy.0001/.dor/rights.dor.json.json
{
  "id": "info:root/xyzzy.0001/rights.dor.json",
  "parent": "info:root/xyzzy.0001",
  "systemIdentifier": "041d2be2-afcb-5ddb-897e-fab30a49a9d2",
  "interactionModel": "urn:umich:lib:dor:model:2026:rights",
  "contentSize": 76,
  "digests": [
    "urn:sha-512:3e175d75f5fd9bc4b548c1a235b9d4300775c1cc8dd16c64eb5be0a2ed049d6bf2670ca5d6c2a9b7f92a51f6c2a72f5b626e948c18914895c765ea8e02ee5478"
  ],
  "updatedAt": "2026-03-16T15:35:36Z",
  "updatedBy": "dlxsadm",
  "deleted": false,
  "visibility": "visible",
  "contentPath": "rights.dor.json",
  "headersVersion": "1.0"
}

=== respinos/glam-sample-generator-rb/examples/nested/clark1ic.000080674/.dor/rights.dor.json.json
{
  "id": "info:root/clark1ic.000080674/rights.dor.json",
  "parent": "info:root/clark1ic.000080674",
  "systemIdentifier": "df5b6319-934d-582d-867d-db9fa40c7d72",
  "interactionModel": "urn:umich:lib:dor:model:2026:rights",
  "contentSize": 669,
  "digests": [
    "urn:sha-512:efdd48ebe502c41ff75bb243c97b1f572b777683bea75240a5be0d6cf3d899420fad604cb3244b45772b0064424b6d93f28694c452be97d4ec4164f8b9467ee5"
  ],
  "updatedAt": "2026-01-30T16:33:55-05:00",
  "updatedBy": "dlxsadm",
  "deleted": false,
  "visibility": "visible",
  "contentPath": "rights.dor.json",
  "headersVersion": "1.0"
}
